wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715494035
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      3:
      - 23
      4: 3.12.3
      5: 0.17.0
      6: 4.40.2
      8:
      - 5
      13: linux-x86_64
pretrained_model_name_or_path:
  desc: null
  value: runwayml/stable-diffusion-v1-5
revision:
  desc: null
  value: null
variant:
  desc: null
  value: null
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
train_data_dir:
  desc: null
  value: ./data
image_column:
  desc: null
  value: image
caption_column:
  desc: null
  value: text
validation_prompt:
  desc: null
  value: expansion joint.
num_validation_images:
  desc: null
  value: 4
validation_epochs:
  desc: null
  value: 1
max_train_samples:
  desc: null
  value: null
output_dir:
  desc: null
  value: ./output
cache_dir:
  desc: null
  value: null
seed:
  desc: null
  value: 1337
resolution:
  desc: null
  value: 512
center_crop:
  desc: null
  value: true
random_flip:
  desc: null
  value: true
train_batch_size:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 1667
max_train_steps:
  desc: null
  value: 15000
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0001
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: cosine
lr_warmup_steps:
  desc: null
  value: 0
snr_gamma:
  desc: null
  value: null
use_8bit_adam:
  desc: null
  value: false
allow_tf32:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 8
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: true
hub_token:
  desc: null
  value: null
prediction_type:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: expansion_joint-lora
logging_dir:
  desc: null
  value: logs
mixed_precision:
  desc: null
  value: null
report_to:
  desc: null
  value: wandb
local_rank:
  desc: null
  value: -1
checkpointing_steps:
  desc: null
  value: 500
checkpoints_total_limit:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
enable_xformers_memory_efficient_attention:
  desc: null
  value: false
noise_offset:
  desc: null
  value: 0
rank:
  desc: null
  value: 4
